trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'macos-latest'

stages:
- stage: VALUE_UPDATE
  condition: eq(variables['Build.Reason'], 'Manual')
  jobs:
    - job: Updating rule
      steps:
        - script: bundle update
          displayName: 'update bundle'

        - script: bundle install
          displayName: 'install bundle'

        - script: |
            echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
            echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
          displayName: "Set java version"

        - task: GooglePlay@4
          displayName: Update data safety rule
          inputs:
            operation: 'Update data safety rule'
            serviceAccountCredentials: 'api-play-store.json'
            dataSafetyCSV: 'my_export.csv'
            appPackageName: 'com.example.circularimage.circularimageview'
