trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'macos-latest'

stages:
- stage: value
  condition: eq(variables['Build.Reason'], 'Manual')
  jobs:
    - job: Updating rule
      steps:
        - script: bundle update
          displayName: 'update bundle'

        - script: bundle install
          displayName: 'install bundle'

        - script: |
            echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
            echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
          displayName: "Set java version"
